baseURL = "http://example.org/"
languageCode = "en-us"
title = "example"
theme = "hugo-theme-tex"
[params]
    darkMode = true
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true